version: '3.3'

services:
  api:
    build: ./cake_service
    image: cake-service:latest
    expose:
      - 80
    environment:
      DB_URI: "mongodb://mongo:27017"
      APP_PORT: :80
      WAIT_HOSTS: mongo:27017
    links:
      - mongo
    depends_on:
      - mongo

  web:
    build: ./cakes_web
    image: cake-web:latest
    expose:
      - 80

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - api
      - web

  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./data:/data/db

volumes:
  mongo_data:
